version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/tackeyy/ticky/cmd.version={{.Version}}
      - -X github.com/tackeyy/ticky/cmd.commit={{.Commit}}
      - -X github.com/tackeyy/ticky/cmd.date={{.Date}}

archives:
  - formats:
      - tar.gz

nfpms:
  - package_name: ticky
    vendor: tackeyy
    homepage: https://github.com/tackeyy/ticky
    maintainer: tackeyy
    description: A CLI tool for TickTick task management
    license: MIT
    formats:
      - deb
      - rpm

brews:
  - repository:
      owner: tackeyy
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/tackeyy/ticky
    description: A CLI tool for TickTick task management
