name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below to help us fix it.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
      placeholder: |
        When I run `ticky tasks create --title "Test" --priority high`, I get an error...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run `ticky tasks create --title "Test" --priority high`
        2. Observe error message
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen
      placeholder: Task should be created successfully
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened (include error messages if any)
      placeholder: |
        Error: not authenticated: run 'ticky auth login' first
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: ticky version
      description: Run `ticky --version`
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: go
    attributes:
      label: Go version
      description: Run `go version`
      placeholder: "go1.25.2 darwin/arm64"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: e.g., macOS 15.3, Ubuntu 24.04, Windows 11
      placeholder: "macOS 15.3"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other context, screenshots, or logs that might help
    validations:
      required: false
